version: '3.9'

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    container_name: $DB_CONTAINER_NAME
    ports:
      - '3360:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - spring_mysql:/var/lib/mysql

  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpmyadmin-ideas
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
    links:
      - 'mysql:db'
    ports:
      - '8070:80'

volumes:
  spring_mysql:
    external: true
