spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: mySecretPass23nsdf
    driver-class-name: org.postgresql.Driver   # buscara el mejor driver para PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update  # c/levante el project se actualizaran las tablas basado en el schema/models
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
